#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHangTiecCuoi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhaHang")]
	public partial class DBNhaHangTiecCuoiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertBOPHAN(BOPHAN instance);
    partial void UpdateBOPHAN(BOPHAN instance);
    partial void DeleteBOPHAN(BOPHAN instance);
    partial void InsertDATTIEC(DATTIEC instance);
    partial void UpdateDATTIEC(DATTIEC instance);
    partial void DeleteDATTIEC(DATTIEC instance);
    partial void InsertDICHVU(DICHVU instance);
    partial void UpdateDICHVU(DICHVU instance);
    partial void DeleteDICHVU(DICHVU instance);
    partial void InsertDICHVU_DATTIEC(DICHVU_DATTIEC instance);
    partial void UpdateDICHVU_DATTIEC(DICHVU_DATTIEC instance);
    partial void DeleteDICHVU_DATTIEC(DICHVU_DATTIEC instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertMONAN(MONAN instance);
    partial void UpdateMONAN(MONAN instance);
    partial void DeleteMONAN(MONAN instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertSanh(Sanh instance);
    partial void UpdateSanh(Sanh instance);
    partial void DeleteSanh(Sanh instance);
    partial void InsertTHUCDON(THUCDON instance);
    partial void UpdateTHUCDON(THUCDON instance);
    partial void DeleteTHUCDON(THUCDON instance);
    partial void InsertTHUCDON_MONAN(THUCDON_MONAN instance);
    partial void UpdateTHUCDON_MONAN(THUCDON_MONAN instance);
    partial void DeleteTHUCDON_MONAN(THUCDON_MONAN instance);
    #endregion
		
		public DBNhaHangTiecCuoiDataContext() : 
				base(global::QLNhaHangTiecCuoi.Properties.Settings.Default.QLNhaHangConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBNhaHangTiecCuoiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBNhaHangTiecCuoiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBNhaHangTiecCuoiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBNhaHangTiecCuoiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<BOPHAN> BOPHANs
		{
			get
			{
				return this.GetTable<BOPHAN>();
			}
		}
		
		public System.Data.Linq.Table<DATTIEC> DATTIECs
		{
			get
			{
				return this.GetTable<DATTIEC>();
			}
		}
		
		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}
		
		public System.Data.Linq.Table<DICHVU_DATTIEC> DICHVU_DATTIECs
		{
			get
			{
				return this.GetTable<DICHVU_DATTIEC>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<MONAN> MONANs
		{
			get
			{
				return this.GetTable<MONAN>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<Sanh> Sanhs
		{
			get
			{
				return this.GetTable<Sanh>();
			}
		}
		
		public System.Data.Linq.Table<THUCDON> THUCDONs
		{
			get
			{
				return this.GetTable<THUCDON>();
			}
		}
		
		public System.Data.Linq.Table<THUCDON_MONAN> THUCDON_MONANs
		{
			get
			{
				return this.GetTable<THUCDON_MONAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _TypeUser;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnTypeUserChanging(string value);
    partial void OnTypeUserChanged();
    #endregion
		
		public ACCOUNT()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeUser", DbType="Char(10)")]
		public string TypeUser
		{
			get
			{
				return this._TypeUser;
			}
			set
			{
				if ((this._TypeUser != value))
				{
					this.OnTypeUserChanging(value);
					this.SendPropertyChanging();
					this._TypeUser = value;
					this.SendPropertyChanged("TypeUser");
					this.OnTypeUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_KHACHHANG", Storage="_KHACHHANGs", ThisKey="UserName", OtherKey="UserName")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_NHANVIEN", Storage="_NHANVIENs", ThisKey="UserName", OtherKey="UserName")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = null;
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BOPHAN")]
	public partial class BOPHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBP;
		
		private string _TenBP;
		
		private System.Nullable<int> _SoLuongNV;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBPChanging(string value);
    partial void OnMaBPChanged();
    partial void OnTenBPChanging(string value);
    partial void OnTenBPChanged();
    partial void OnSoLuongNVChanging(System.Nullable<int> value);
    partial void OnSoLuongNVChanged();
    #endregion
		
		public BOPHAN()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBP
		{
			get
			{
				return this._MaBP;
			}
			set
			{
				if ((this._MaBP != value))
				{
					this.OnMaBPChanging(value);
					this.SendPropertyChanging();
					this._MaBP = value;
					this.SendPropertyChanged("MaBP");
					this.OnMaBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBP", DbType="NVarChar(20)")]
		public string TenBP
		{
			get
			{
				return this._TenBP;
			}
			set
			{
				if ((this._TenBP != value))
				{
					this.OnTenBPChanging(value);
					this.SendPropertyChanging();
					this._TenBP = value;
					this.SendPropertyChanged("TenBP");
					this.OnTenBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNV", DbType="Int")]
		public System.Nullable<int> SoLuongNV
		{
			get
			{
				return this._SoLuongNV;
			}
			set
			{
				if ((this._SoLuongNV != value))
				{
					this.OnSoLuongNVChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNV = value;
					this.SendPropertyChanged("SoLuongNV");
					this.OnSoLuongNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOPHAN_NHANVIEN", Storage="_NHANVIENs", ThisKey="MaBP", OtherKey="MaBP")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BOPHAN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BOPHAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATTIEC")]
	public partial class DATTIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTiec;
		
		private string _MaSanh;
		
		private string _MaNV;
		
		private string _MaKH;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<System.DateTime> _NgayToChuc;
		
		private System.Nullable<int> _SoLuongBan;
		
		private System.Nullable<int> _SoLuongKhach;
		
		private string _Buoi;
		
		private string _TinhTrang;
		
		private EntitySet<DICHVU_DATTIEC> _DICHVU_DATTIECs;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<THUCDON> _THUCDONs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<Sanh> _Sanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    partial void OnMaSanhChanging(string value);
    partial void OnMaSanhChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNgayToChucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayToChucChanged();
    partial void OnSoLuongBanChanging(System.Nullable<int> value);
    partial void OnSoLuongBanChanged();
    partial void OnSoLuongKhachChanging(System.Nullable<int> value);
    partial void OnSoLuongKhachChanged();
    partial void OnBuoiChanging(string value);
    partial void OnBuoiChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public DATTIEC()
		{
			this._DICHVU_DATTIECs = new EntitySet<DICHVU_DATTIEC>(new Action<DICHVU_DATTIEC>(this.attach_DICHVU_DATTIECs), new Action<DICHVU_DATTIEC>(this.detach_DICHVU_DATTIECs));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._THUCDONs = new EntitySet<THUCDON>(new Action<THUCDON>(this.attach_THUCDONs), new Action<THUCDON>(this.detach_THUCDONs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._Sanh = default(EntityRef<Sanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanh", DbType="Char(10)")]
		public string MaSanh
		{
			get
			{
				return this._MaSanh;
			}
			set
			{
				if ((this._MaSanh != value))
				{
					if (this._Sanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanhChanging(value);
					this.SendPropertyChanging();
					this._MaSanh = value;
					this.SendPropertyChanged("MaSanh");
					this.OnMaSanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayToChuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayToChuc
		{
			get
			{
				return this._NgayToChuc;
			}
			set
			{
				if ((this._NgayToChuc != value))
				{
					this.OnNgayToChucChanging(value);
					this.SendPropertyChanging();
					this._NgayToChuc = value;
					this.SendPropertyChanged("NgayToChuc");
					this.OnNgayToChucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBan", DbType="Int")]
		public System.Nullable<int> SoLuongBan
		{
			get
			{
				return this._SoLuongBan;
			}
			set
			{
				if ((this._SoLuongBan != value))
				{
					this.OnSoLuongBanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBan = value;
					this.SendPropertyChanged("SoLuongBan");
					this.OnSoLuongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongKhach", DbType="Int")]
		public System.Nullable<int> SoLuongKhach
		{
			get
			{
				return this._SoLuongKhach;
			}
			set
			{
				if ((this._SoLuongKhach != value))
				{
					this.OnSoLuongKhachChanging(value);
					this.SendPropertyChanging();
					this._SoLuongKhach = value;
					this.SendPropertyChanged("SoLuongKhach");
					this.OnSoLuongKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buoi", DbType="NVarChar(20)")]
		public string Buoi
		{
			get
			{
				return this._Buoi;
			}
			set
			{
				if ((this._Buoi != value))
				{
					this.OnBuoiChanging(value);
					this.SendPropertyChanging();
					this._Buoi = value;
					this.SendPropertyChanged("Buoi");
					this.OnBuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DICHVU_DATTIEC", Storage="_DICHVU_DATTIECs", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<DICHVU_DATTIEC> DICHVU_DATTIECs
		{
			get
			{
				return this._DICHVU_DATTIECs;
			}
			set
			{
				this._DICHVU_DATTIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_HOADON", Storage="_HOADONs", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_THUCDON", Storage="_THUCDONs", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<THUCDON> THUCDONs
		{
			get
			{
				return this._THUCDONs;
			}
			set
			{
				this._THUCDONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATTIEC", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DATTIECs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DATTIECs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DATTIEC", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.DATTIECs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.DATTIECs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanh_DATTIEC", Storage="_Sanh", ThisKey="MaSanh", OtherKey="MaSanh", IsForeignKey=true)]
		public Sanh Sanh
		{
			get
			{
				return this._Sanh.Entity;
			}
			set
			{
				Sanh previousValue = this._Sanh.Entity;
				if (((previousValue != value) 
							|| (this._Sanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sanh.Entity = null;
						previousValue.DATTIECs.Remove(this);
					}
					this._Sanh.Entity = value;
					if ((value != null))
					{
						value.DATTIECs.Add(this);
						this._MaSanh = value.MaSanh;
					}
					else
					{
						this._MaSanh = default(string);
					}
					this.SendPropertyChanged("Sanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DICHVU_DATTIECs(DICHVU_DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = this;
		}
		
		private void detach_DICHVU_DATTIECs(DICHVU_DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = null;
		}
		
		private void attach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = this;
		}
		
		private void detach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private System.Nullable<decimal> _DonGia;
		
		private EntitySet<DICHVU_DATTIEC> _DICHVU_DATTIECs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public DICHVU()
		{
			this._DICHVU_DATTIECs = new EntitySet<DICHVU_DATTIEC>(new Action<DICHVU_DATTIEC>(this.attach_DICHVU_DATTIECs), new Action<DICHVU_DATTIEC>(this.detach_DICHVU_DATTIECs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_DICHVU_DATTIEC", Storage="_DICHVU_DATTIECs", ThisKey="MaDV", OtherKey="MaDV")]
		public EntitySet<DICHVU_DATTIEC> DICHVU_DATTIECs
		{
			get
			{
				return this._DICHVU_DATTIECs;
			}
			set
			{
				this._DICHVU_DATTIECs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DICHVU_DATTIECs(DICHVU_DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = this;
		}
		
		private void detach_DICHVU_DATTIECs(DICHVU_DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU_DATTIEC")]
	public partial class DICHVU_DATTIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _MaTiec;
		
		private EntityRef<DATTIEC> _DATTIEC;
		
		private EntityRef<DICHVU> _DICHVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    #endregion
		
		public DICHVU_DATTIEC()
		{
			this._DATTIEC = default(EntityRef<DATTIEC>);
			this._DICHVU = default(EntityRef<DICHVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					if (this._DICHVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					if (this._DATTIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DICHVU_DATTIEC", Storage="_DATTIEC", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true)]
		public DATTIEC DATTIEC
		{
			get
			{
				return this._DATTIEC.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC.Entity = null;
						previousValue.DICHVU_DATTIECs.Remove(this);
					}
					this._DATTIEC.Entity = value;
					if ((value != null))
					{
						value.DICHVU_DATTIECs.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_DICHVU_DATTIEC", Storage="_DICHVU", ThisKey="MaDV", OtherKey="MaDV", IsForeignKey=true)]
		public DICHVU DICHVU
		{
			get
			{
				return this._DICHVU.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU.Entity;
				if (((previousValue != value) 
							|| (this._DICHVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU.Entity = null;
						previousValue.DICHVU_DATTIECs.Remove(this);
					}
					this._DICHVU.Entity = value;
					if ((value != null))
					{
						value.DICHVU_DATTIECs.Add(this);
						this._MaDV = value.MaDV;
					}
					else
					{
						this._MaDV = default(string);
					}
					this.SendPropertyChanged("DICHVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaTiec;
		
		private string _MaKh;
		
		private string _MaNV;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private string _TinhTrang;
		
		private EntityRef<DATTIEC> _DATTIEC;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    partial void OnMaKhChanging(string value);
    partial void OnMaKhChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public HOADON()
		{
			this._DATTIEC = default(EntityRef<DATTIEC>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10)")]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					if (this._DATTIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKh", DbType="Char(10)")]
		public string MaKh
		{
			get
			{
				return this._MaKh;
			}
			set
			{
				if ((this._MaKh != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhChanging(value);
					this.SendPropertyChanging();
					this._MaKh = value;
					this.SendPropertyChanged("MaKh");
					this.OnMaKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_HOADON", Storage="_DATTIEC", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true)]
		public DATTIEC DATTIEC
		{
			get
			{
				return this._DATTIEC.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._DATTIEC.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="MaKh", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaKh = value.MaKH;
					}
					else
					{
						this._MaKh = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _GioiTinh;
		
		private string _CMND;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _UserName;
		
		private EntitySet<DATTIEC> _DATTIECs;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<ACCOUNT> _ACCOUNT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._DATTIECs = new EntitySet<DATTIEC>(new Action<DATTIEC>(this.attach_DATTIECs), new Action<DATTIEC>(this.detach_DATTIECs));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._ACCOUNT = default(EntityRef<ACCOUNT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(15)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="Char(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					if (this._ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATTIEC", Storage="_DATTIECs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DATTIEC> DATTIECs
		{
			get
			{
				return this._DATTIECs;
			}
			set
			{
				this._DATTIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="MaKH", OtherKey="MaKh")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_KHACHHANG", Storage="_ACCOUNT", ThisKey="UserName", OtherKey="UserName", IsForeignKey=true)]
		public ACCOUNT ACCOUNT
		{
			get
			{
				return this._ACCOUNT.Entity;
			}
			set
			{
				ACCOUNT previousValue = this._ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNT.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._UserName = value.UserName;
					}
					else
					{
						this._UserName = default(string);
					}
					this.SendPropertyChanged("ACCOUNT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MONAN")]
	public partial class MONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMA;
		
		private string _TenMa;
		
		private System.Nullable<decimal> _Gia;
		
		private string _Loai;
		
		private string _DonViTinh;
		
		private EntitySet<THUCDON_MONAN> _THUCDON_MONANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMAChanging(string value);
    partial void OnMaMAChanged();
    partial void OnTenMaChanging(string value);
    partial void OnTenMaChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    #endregion
		
		public MONAN()
		{
			this._THUCDON_MONANs = new EntitySet<THUCDON_MONAN>(new Action<THUCDON_MONAN>(this.attach_THUCDON_MONANs), new Action<THUCDON_MONAN>(this.detach_THUCDON_MONANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMA
		{
			get
			{
				return this._MaMA;
			}
			set
			{
				if ((this._MaMA != value))
				{
					this.OnMaMAChanging(value);
					this.SendPropertyChanging();
					this._MaMA = value;
					this.SendPropertyChanged("MaMA");
					this.OnMaMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMa", DbType="NVarChar(50)")]
		public string TenMa
		{
			get
			{
				return this._TenMa;
			}
			set
			{
				if ((this._TenMa != value))
				{
					this.OnTenMaChanging(value);
					this.SendPropertyChanging();
					this._TenMa = value;
					this.SendPropertyChanged("TenMa");
					this.OnTenMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(10)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(10)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_THUCDON_MONAN", Storage="_THUCDON_MONANs", ThisKey="MaMA", OtherKey="MaMA")]
		public EntitySet<THUCDON_MONAN> THUCDON_MONANs
		{
			get
			{
				return this._THUCDON_MONANs;
			}
			set
			{
				this._THUCDON_MONANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THUCDON_MONANs(THUCDON_MONAN entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = this;
		}
		
		private void detach_THUCDON_MONANs(THUCDON_MONAN entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _SDT;
		
		private string _CMND;
		
		private string _MaBP;
		
		private string _ChucVu;
		
		private System.Nullable<decimal> _Luong;
		
		private string _UserName;
		
		private EntitySet<DATTIEC> _DATTIECs;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<ACCOUNT> _ACCOUNT;
		
		private EntityRef<BOPHAN> _BOPHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnMaBPChanging(string value);
    partial void OnMaBPChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnLuongChanging(System.Nullable<decimal> value);
    partial void OnLuongChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._DATTIECs = new EntitySet<DATTIEC>(new Action<DATTIEC>(this.attach_DATTIECs), new Action<DATTIEC>(this.detach_DATTIECs));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._ACCOUNT = default(EntityRef<ACCOUNT>);
			this._BOPHAN = default(EntityRef<BOPHAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBP", DbType="Char(10)")]
		public string MaBP
		{
			get
			{
				return this._MaBP;
			}
			set
			{
				if ((this._MaBP != value))
				{
					if (this._BOPHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBPChanging(value);
					this.SendPropertyChanging();
					this._MaBP = value;
					this.SendPropertyChanged("MaBP");
					this.OnMaBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(20)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="Char(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					if (this._ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DATTIEC", Storage="_DATTIECs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<DATTIEC> DATTIECs
		{
			get
			{
				return this._DATTIECs;
			}
			set
			{
				this._DATTIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_HOADONs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_NHANVIEN", Storage="_ACCOUNT", ThisKey="UserName", OtherKey="UserName", IsForeignKey=true)]
		public ACCOUNT ACCOUNT
		{
			get
			{
				return this._ACCOUNT.Entity;
			}
			set
			{
				ACCOUNT previousValue = this._ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNT.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._UserName = value.UserName;
					}
					else
					{
						this._UserName = default(string);
					}
					this.SendPropertyChanged("ACCOUNT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOPHAN_NHANVIEN", Storage="_BOPHAN", ThisKey="MaBP", OtherKey="MaBP", IsForeignKey=true)]
		public BOPHAN BOPHAN
		{
			get
			{
				return this._BOPHAN.Entity;
			}
			set
			{
				BOPHAN previousValue = this._BOPHAN.Entity;
				if (((previousValue != value) 
							|| (this._BOPHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BOPHAN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._BOPHAN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._MaBP = value.MaBP;
					}
					else
					{
						this._MaBP = default(string);
					}
					this.SendPropertyChanged("BOPHAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sanh")]
	public partial class Sanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSanh;
		
		private string _TenSanh;
		
		private string _Tang;
		
		private System.Nullable<decimal> _DonGia;
		
		private System.Nullable<int> _SucChua;
		
		private EntitySet<DATTIEC> _DATTIECs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanhChanging(string value);
    partial void OnMaSanhChanged();
    partial void OnTenSanhChanging(string value);
    partial void OnTenSanhChanged();
    partial void OnTangChanging(string value);
    partial void OnTangChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnSucChuaChanging(System.Nullable<int> value);
    partial void OnSucChuaChanged();
    #endregion
		
		public Sanh()
		{
			this._DATTIECs = new EntitySet<DATTIEC>(new Action<DATTIEC>(this.attach_DATTIECs), new Action<DATTIEC>(this.detach_DATTIECs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanh", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanh
		{
			get
			{
				return this._MaSanh;
			}
			set
			{
				if ((this._MaSanh != value))
				{
					this.OnMaSanhChanging(value);
					this.SendPropertyChanging();
					this._MaSanh = value;
					this.SendPropertyChanged("MaSanh");
					this.OnMaSanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanh", DbType="NVarChar(20)")]
		public string TenSanh
		{
			get
			{
				return this._TenSanh;
			}
			set
			{
				if ((this._TenSanh != value))
				{
					this.OnTenSanhChanging(value);
					this.SendPropertyChanging();
					this._TenSanh = value;
					this.SendPropertyChanged("TenSanh");
					this.OnTenSanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tang", DbType="Char(10)")]
		public string Tang
		{
			get
			{
				return this._Tang;
			}
			set
			{
				if ((this._Tang != value))
				{
					this.OnTangChanging(value);
					this.SendPropertyChanging();
					this._Tang = value;
					this.SendPropertyChanged("Tang");
					this.OnTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChua", DbType="Int")]
		public System.Nullable<int> SucChua
		{
			get
			{
				return this._SucChua;
			}
			set
			{
				if ((this._SucChua != value))
				{
					this.OnSucChuaChanging(value);
					this.SendPropertyChanging();
					this._SucChua = value;
					this.SendPropertyChanged("SucChua");
					this.OnSucChuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanh_DATTIEC", Storage="_DATTIECs", ThisKey="MaSanh", OtherKey="MaSanh")]
		public EntitySet<DATTIEC> DATTIECs
		{
			get
			{
				return this._DATTIECs;
			}
			set
			{
				this._DATTIECs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.Sanh = this;
		}
		
		private void detach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.Sanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUCDON")]
	public partial class THUCDON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTD;
		
		private string _MaTiec;
		
		private System.Nullable<System.DateTime> _NgaySD;
		
		private EntitySet<THUCDON_MONAN> _THUCDON_MONANs;
		
		private EntityRef<DATTIEC> _DATTIEC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    partial void OnNgaySDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySDChanged();
    #endregion
		
		public THUCDON()
		{
			this._THUCDON_MONANs = new EntitySet<THUCDON_MONAN>(new Action<THUCDON_MONAN>(this.attach_THUCDON_MONANs), new Action<THUCDON_MONAN>(this.detach_THUCDON_MONANs));
			this._DATTIEC = default(EntityRef<DATTIEC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10)")]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					if (this._DATTIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySD
		{
			get
			{
				return this._NgaySD;
			}
			set
			{
				if ((this._NgaySD != value))
				{
					this.OnNgaySDChanging(value);
					this.SendPropertyChanging();
					this._NgaySD = value;
					this.SendPropertyChanged("NgaySD");
					this.OnNgaySDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCDON_THUCDON_MONAN", Storage="_THUCDON_MONANs", ThisKey="MaTD", OtherKey="MaTD")]
		public EntitySet<THUCDON_MONAN> THUCDON_MONANs
		{
			get
			{
				return this._THUCDON_MONANs;
			}
			set
			{
				this._THUCDON_MONANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_THUCDON", Storage="_DATTIEC", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true)]
		public DATTIEC DATTIEC
		{
			get
			{
				return this._DATTIEC.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC.Entity = null;
						previousValue.THUCDONs.Remove(this);
					}
					this._DATTIEC.Entity = value;
					if ((value != null))
					{
						value.THUCDONs.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THUCDON_MONANs(THUCDON_MONAN entity)
		{
			this.SendPropertyChanging();
			entity.THUCDON = this;
		}
		
		private void detach_THUCDON_MONANs(THUCDON_MONAN entity)
		{
			this.SendPropertyChanging();
			entity.THUCDON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUCDON_MONAN")]
	public partial class THUCDON_MONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTD;
		
		private string _MaMA;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntityRef<MONAN> _MONAN;
		
		private EntityRef<THUCDON> _THUCDON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    partial void OnMaMAChanging(string value);
    partial void OnMaMAChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public THUCDON_MONAN()
		{
			this._MONAN = default(EntityRef<MONAN>);
			this._THUCDON = default(EntityRef<THUCDON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					if (this._THUCDON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMA
		{
			get
			{
				return this._MaMA;
			}
			set
			{
				if ((this._MaMA != value))
				{
					if (this._MONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMAChanging(value);
					this.SendPropertyChanging();
					this._MaMA = value;
					this.SendPropertyChanged("MaMA");
					this.OnMaMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_THUCDON_MONAN", Storage="_MONAN", ThisKey="MaMA", OtherKey="MaMA", IsForeignKey=true)]
		public MONAN MONAN
		{
			get
			{
				return this._MONAN.Entity;
			}
			set
			{
				MONAN previousValue = this._MONAN.Entity;
				if (((previousValue != value) 
							|| (this._MONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONAN.Entity = null;
						previousValue.THUCDON_MONANs.Remove(this);
					}
					this._MONAN.Entity = value;
					if ((value != null))
					{
						value.THUCDON_MONANs.Add(this);
						this._MaMA = value.MaMA;
					}
					else
					{
						this._MaMA = default(string);
					}
					this.SendPropertyChanged("MONAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCDON_THUCDON_MONAN", Storage="_THUCDON", ThisKey="MaTD", OtherKey="MaTD", IsForeignKey=true)]
		public THUCDON THUCDON
		{
			get
			{
				return this._THUCDON.Entity;
			}
			set
			{
				THUCDON previousValue = this._THUCDON.Entity;
				if (((previousValue != value) 
							|| (this._THUCDON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUCDON.Entity = null;
						previousValue.THUCDON_MONANs.Remove(this);
					}
					this._THUCDON.Entity = value;
					if ((value != null))
					{
						value.THUCDON_MONANs.Add(this);
						this._MaTD = value.MaTD;
					}
					else
					{
						this._MaTD = default(string);
					}
					this.SendPropertyChanged("THUCDON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
