#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHangTiecCuoi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhaHang")]
	public partial class DBQuanLyNhaHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertSanh(Sanh instance);
    partial void UpdateSanh(Sanh instance);
    partial void DeleteSanh(Sanh instance);
    partial void InsertBOPHAN(BOPHAN instance);
    partial void UpdateBOPHAN(BOPHAN instance);
    partial void DeleteBOPHAN(BOPHAN instance);
    partial void InsertDATDICHVU(DATDICHVU instance);
    partial void UpdateDATDICHVU(DATDICHVU instance);
    partial void DeleteDATDICHVU(DATDICHVU instance);
    partial void InsertDATMONAN(DATMONAN instance);
    partial void UpdateDATMONAN(DATMONAN instance);
    partial void DeleteDATMONAN(DATMONAN instance);
    partial void InsertDATTIEC(DATTIEC instance);
    partial void UpdateDATTIEC(DATTIEC instance);
    partial void DeleteDATTIEC(DATTIEC instance);
    partial void InsertDICHVU(DICHVU instance);
    partial void UpdateDICHVU(DICHVU instance);
    partial void DeleteDICHVU(DICHVU instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertMONAN(MONAN instance);
    partial void UpdateMONAN(MONAN instance);
    partial void DeleteMONAN(MONAN instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    #endregion
		
		public DBQuanLyNhaHangDataContext() : 
				base(global::QLNhaHangTiecCuoi.Properties.Settings.Default.QLNhaHangConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLyNhaHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLyNhaHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLyNhaHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLyNhaHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<Sanh> Sanhs
		{
			get
			{
				return this.GetTable<Sanh>();
			}
		}
		
		public System.Data.Linq.Table<BOPHAN> BOPHANs
		{
			get
			{
				return this.GetTable<BOPHAN>();
			}
		}
		
		public System.Data.Linq.Table<DATDICHVU> DATDICHVUs
		{
			get
			{
				return this.GetTable<DATDICHVU>();
			}
		}
		
		public System.Data.Linq.Table<DATMONAN> DATMONANs
		{
			get
			{
				return this.GetTable<DATMONAN>();
			}
		}
		
		public System.Data.Linq.Table<DATTIEC> DATTIECs
		{
			get
			{
				return this.GetTable<DATTIEC>();
			}
		}
		
		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<MONAN> MONANs
		{
			get
			{
				return this.GetTable<MONAN>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListDichVuDat")]
		public ISingleResult<ListDichVuDatResult> ListDichVuDat([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTiec", DbType="Char(10)")] string maTiec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec);
			return ((ISingleResult<ListDichVuDatResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TongThanhTien", IsComposable=true)]
		public string TongThanhTien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddAccount")]
		public int pr_AddAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="Char(20)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="Char(20)")] string passWord, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeUser", DbType="Char(10)")] string typeUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passWord, typeUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddBoPhan")]
		public int pr_AddBoPhan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBP", DbType="NVarChar(20)")] string tenBP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenBP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddDatDV")]
		public int pr_AddDatDV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTiec", DbType="Char(10)")] string maTiec, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDV", DbType="Char(10)")] string maDV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec, maDV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddDatMon")]
		public int pr_AddDatMon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTiec", DbType="Char(10)")] string maTiec, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMA", DbType="Char(10)")] string maMA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec, maMA, soLuong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddDatSanh")]
		public int pr_AddDatSanh([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTiec", DbType="Char(10)")] string maTiec, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSanh", DbType="Char(10)")] string maSanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayToChuc", DbType="DateTime")] System.Nullable<System.DateTime> ngayToChuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Buoi", DbType="NVarChar(20)")] string buoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec, maSanh, ngayToChuc, buoi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_addDatTiec")]
		public int pr_addDatTiec([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKH", DbType="Char(10)")] string maKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTiec", DbType="NVarChar(50)")] string tenTiec, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SLBan", DbType="Int")] System.Nullable<int> sLBan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SLKhach", DbType="Int")] System.Nullable<int> sLKhach)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH, tenTiec, sLBan, sLKhach);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddDichVu")]
		public int pr_AddDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenDV", DbType="NVarChar(50)")] string tenDV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenDV, donGia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_addHoaDon")]
		public int pr_addHoaDon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTiec", DbType="Char(10)")] string maTiec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddKhachHang")]
		public int pr_AddKhachHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenKH", DbType="NVarChar(50)")] string tenKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Char(10)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="Char(10)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(11)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="Char(20)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="Char(10)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenKH, gioiTinh, cMND, sDT, diaChi, username, passWord);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddMonAn")]
		public int pr_AddMonAn([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenMA", DbType="NVarChar(50)")] string tenMA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Loai", DbType="NVarChar(10)")] string loai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonViTinh", DbType="NVarChar(10)")] string donViTinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenMA, donGia, loai, donViTinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddNhanVien")]
		public int pr_AddNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenNV", DbType="NVarChar(50)")] string tenNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(11)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="Char(10)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBP", DbType="Char(10)")] string maBP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChucVu", DbType="NVarChar(20)")] string chucVu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Luong", DbType="Decimal(18,0)")] System.Nullable<decimal> luong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="Char(20)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="Char(20)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenNV, sDT, cMND, maBP, chucVu, luong, username, passWord);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddSanh")]
		public int pr_AddSanh([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSanh", DbType="NVarChar(20)")] string tenSanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tang", DbType="Char(10)")] string tang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SucChua", DbType="Int")] System.Nullable<int> sucChua)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenSanh, tang, donGia, sucChua);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SuaBoPhan")]
		public int pr_SuaBoPhan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBP", DbType="Char(10)")] string maBP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBP", DbType="NVarChar(20)")] string tenBP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBP, tenBP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SuaDatMon")]
		public int pr_SuaDatMon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTiec", DbType="Char(10)")] string maTiec, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMA", DbType="Char(10)")] string maMA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec, maMA, soLuong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SuaDichVu")]
		public int pr_SuaDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDV", DbType="Char(10)")] string maDV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenDV", DbType="NVarChar(50)")] string tenDV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maDV, tenDV, donGia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SuaKhachhang")]
		public int pr_SuaKhachhang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKH", DbType="Char(10)")] string maKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenKH", DbType="NVarChar(50)")] string tenKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NChar(10)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="Char(15)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDT", DbType="Char(11)")] string soDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH, tenKH, gioiTinh, cMND, soDT, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SuaMonAn")]
		public int pr_SuaMonAn([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMA", DbType="Char(10)")] string maMA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenMA", DbType="NVarChar(50)")] string tenMA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gia", DbType="Decimal(18,0)")] System.Nullable<decimal> gia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Loai", DbType="NVarChar(10)")] string loai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonViTinh", DbType="NVarChar(10)")] string donViTinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMA, tenMA, gia, loai, donViTinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SuaNhanVien")]
		public int pr_SuaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Char(10)")] string maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenNV", DbType="NVarChar(50)")] string tenNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(11)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="Char(10)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBP", DbType="Char(10)")] string maBP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChucVu", DbType="NVarChar(20)")] string chucVu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Luong", DbType="Decimal(18,0)")] System.Nullable<decimal> luong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, tenNV, sDT, cMND, maBP, chucVu, luong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SuaSanh")]
		public int pr_SuaSanh([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSanh", DbType="Char(10)")] string maSanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSanh", DbType="NVarChar(20)")] string tenSanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tang", DbType="Char(10)")] string tang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SucChua", DbType="Int")] System.Nullable<int> sucChua)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSanh, tenSanh, tang, donGia, sucChua);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_Xoa1DatDichVu")]
		public int pr_Xoa1DatDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maDV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec, maDV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_Xoa1DatMonAn")]
		public int pr_Xoa1DatMonAn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maMonAn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec, maMonAn);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaAccount")]
		public int pr_XoaAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="Char(20)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaAllDatDichVu")]
		public int pr_XoaAllDatDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaAllDatMonAn")]
		public int pr_XoaAllDatMonAn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaBP")]
		public int pr_XoaBP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBP", DbType="Char(10)")] string maBP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaDatTiec")]
		public int pr_XoaDatTiec([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaHoaDon")]
		public int pr_XoaHoaDon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaKhachHang")]
		public int pr_XoaKhachHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKH", DbType="Char(10)")] string maKH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaNhanVien")]
		public int pr_XoaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Char(10)")] string maNV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaSanh")]
		public int pr_XoaSanh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maSanh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSanh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaThucAn")]
		public int pr_XoaThucAn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maThucAn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maThucAn);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDatMon")]
		public ISingleResult<ShowDatMonResult> ShowDatMon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maTiec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTiec);
			return ((ISingleResult<ShowDatMonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_BP", IsComposable=true)]
		public string Max_BP()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_DatTiec", IsComposable=true)]
		public string Max_DatTiec()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_DV", IsComposable=true)]
		public string Max_DV()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_HD", IsComposable=true)]
		public string Max_HD()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_KH", IsComposable=true)]
		public string Max_KH()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_MA", IsComposable=true)]
		public string Max_MA()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_NV", IsComposable=true)]
		public string Max_NV()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Max_Sanh", IsComposable=true)]
		public string Max_Sanh()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddSanhisDeleted")]
		public int pr_AddSanhisDeleted([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSanh", DbType="NVarChar(20)")] string tenSanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tang", DbType="Char(10)")] string tang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SucChua", DbType="Int")] System.Nullable<int> sucChua)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenSanh, tang, donGia, sucChua);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddMonAnisDeleted")]
		public int pr_AddMonAnisDeleted([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenMA", DbType="NVarChar(50)")] string tenMA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gia", DbType="Decimal(18,0)")] System.Nullable<decimal> gia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Loai", DbType="NVarChar(10)")] string loai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonViTinh", DbType="NVarChar(10)")] string donViTinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenMA, gia, loai, donViTinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_XoaDichVu")]
		public int pr_XoaDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maDichVu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maDichVu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddDichVuisDeleted")]
		public int pr_AddDichVuisDeleted([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenDV", DbType="NVarChar(50)")] string tenDV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gia", DbType="Decimal(18,0)")] System.Nullable<decimal> gia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenDV, gia);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _TypeUser;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnTypeUserChanging(string value);
    partial void OnTypeUserChanged();
    #endregion
		
		public ACCOUNT()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeUser", DbType="Char(10)")]
		public string TypeUser
		{
			get
			{
				return this._TypeUser;
			}
			set
			{
				if ((this._TypeUser != value))
				{
					this.OnTypeUserChanging(value);
					this.SendPropertyChanging();
					this._TypeUser = value;
					this.SendPropertyChanged("TypeUser");
					this.OnTypeUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_KHACHHANG", Storage="_KHACHHANGs", ThisKey="UserName", OtherKey="UserName")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_NHANVIEN", Storage="_NHANVIENs", ThisKey="UserName", OtherKey="UserName")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = null;
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sanh")]
	public partial class Sanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSanh;
		
		private string _TenSanh;
		
		private string _Tang;
		
		private System.Nullable<decimal> _DonGia;
		
		private System.Nullable<int> _SucChua;
		
		private System.Nullable<System.DateTime> _isDeleted;
		
		private EntitySet<DATTIEC> _DATTIECs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanhChanging(string value);
    partial void OnMaSanhChanged();
    partial void OnTenSanhChanging(string value);
    partial void OnTenSanhChanged();
    partial void OnTangChanging(string value);
    partial void OnTangChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnSucChuaChanging(System.Nullable<int> value);
    partial void OnSucChuaChanged();
    partial void OnisDeletedChanging(System.Nullable<System.DateTime> value);
    partial void OnisDeletedChanged();
    #endregion
		
		public Sanh()
		{
			this._DATTIECs = new EntitySet<DATTIEC>(new Action<DATTIEC>(this.attach_DATTIECs), new Action<DATTIEC>(this.detach_DATTIECs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanh", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanh
		{
			get
			{
				return this._MaSanh;
			}
			set
			{
				if ((this._MaSanh != value))
				{
					this.OnMaSanhChanging(value);
					this.SendPropertyChanging();
					this._MaSanh = value;
					this.SendPropertyChanged("MaSanh");
					this.OnMaSanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanh", DbType="NVarChar(20)")]
		public string TenSanh
		{
			get
			{
				return this._TenSanh;
			}
			set
			{
				if ((this._TenSanh != value))
				{
					this.OnTenSanhChanging(value);
					this.SendPropertyChanging();
					this._TenSanh = value;
					this.SendPropertyChanged("TenSanh");
					this.OnTenSanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tang", DbType="Char(10)")]
		public string Tang
		{
			get
			{
				return this._Tang;
			}
			set
			{
				if ((this._Tang != value))
				{
					this.OnTangChanging(value);
					this.SendPropertyChanging();
					this._Tang = value;
					this.SendPropertyChanged("Tang");
					this.OnTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChua", DbType="Int")]
		public System.Nullable<int> SucChua
		{
			get
			{
				return this._SucChua;
			}
			set
			{
				if ((this._SucChua != value))
				{
					this.OnSucChuaChanging(value);
					this.SendPropertyChanging();
					this._SucChua = value;
					this.SendPropertyChanged("SucChua");
					this.OnSucChuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Date")]
		public System.Nullable<System.DateTime> isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanh_DATTIEC", Storage="_DATTIECs", ThisKey="MaSanh", OtherKey="MaSanh")]
		public EntitySet<DATTIEC> DATTIECs
		{
			get
			{
				return this._DATTIECs;
			}
			set
			{
				this._DATTIECs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.Sanh = this;
		}
		
		private void detach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.Sanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BOPHAN")]
	public partial class BOPHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBP;
		
		private string _TenBP;
		
		private System.Nullable<int> _SoLuongNV;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBPChanging(string value);
    partial void OnMaBPChanged();
    partial void OnTenBPChanging(string value);
    partial void OnTenBPChanged();
    partial void OnSoLuongNVChanging(System.Nullable<int> value);
    partial void OnSoLuongNVChanged();
    #endregion
		
		public BOPHAN()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBP
		{
			get
			{
				return this._MaBP;
			}
			set
			{
				if ((this._MaBP != value))
				{
					this.OnMaBPChanging(value);
					this.SendPropertyChanging();
					this._MaBP = value;
					this.SendPropertyChanged("MaBP");
					this.OnMaBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBP", DbType="NVarChar(20)")]
		public string TenBP
		{
			get
			{
				return this._TenBP;
			}
			set
			{
				if ((this._TenBP != value))
				{
					this.OnTenBPChanging(value);
					this.SendPropertyChanging();
					this._TenBP = value;
					this.SendPropertyChanged("TenBP");
					this.OnTenBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNV", DbType="Int")]
		public System.Nullable<int> SoLuongNV
		{
			get
			{
				return this._SoLuongNV;
			}
			set
			{
				if ((this._SoLuongNV != value))
				{
					this.OnSoLuongNVChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNV = value;
					this.SendPropertyChanged("SoLuongNV");
					this.OnSoLuongNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOPHAN_NHANVIEN", Storage="_NHANVIENs", ThisKey="MaBP", OtherKey="MaBP")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BOPHAN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BOPHAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATDICHVU")]
	public partial class DATDICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTiec;
		
		private string _MaDV;
		
		private EntityRef<DATTIEC> _DATTIEC;
		
		private EntityRef<DATTIEC> _DATTIEC1;
		
		private EntityRef<DICHVU> _DICHVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    #endregion
		
		public DATDICHVU()
		{
			this._DATTIEC = default(EntityRef<DATTIEC>);
			this._DATTIEC1 = default(EntityRef<DATTIEC>);
			this._DICHVU = default(EntityRef<DICHVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					if ((this._DATTIEC.HasLoadedOrAssignedValue || this._DATTIEC1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					if (this._DICHVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATDICHVU", Storage="_DATTIEC", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true)]
		public DATTIEC DATTIEC
		{
			get
			{
				return this._DATTIEC.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC.Entity = null;
						previousValue.DATDICHVUs.Remove(this);
					}
					this._DATTIEC.Entity = value;
					if ((value != null))
					{
						value.DATDICHVUs.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATDICHVU1", Storage="_DATTIEC1", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DATTIEC DATTIEC1
		{
			get
			{
				return this._DATTIEC1.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC1.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC1.Entity = null;
						previousValue.DATDICHVUs1.Remove(this);
					}
					this._DATTIEC1.Entity = value;
					if ((value != null))
					{
						value.DATDICHVUs1.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_DATDICHVU", Storage="_DICHVU", ThisKey="MaDV", OtherKey="MaDV", IsForeignKey=true)]
		public DICHVU DICHVU
		{
			get
			{
				return this._DICHVU.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU.Entity;
				if (((previousValue != value) 
							|| (this._DICHVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU.Entity = null;
						previousValue.DATDICHVUs.Remove(this);
					}
					this._DICHVU.Entity = value;
					if ((value != null))
					{
						value.DATDICHVUs.Add(this);
						this._MaDV = value.MaDV;
					}
					else
					{
						this._MaDV = default(string);
					}
					this.SendPropertyChanged("DICHVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATMONAN")]
	public partial class DATMONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTiec;
		
		private string _MaMA;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntityRef<DATTIEC> _DATTIEC;
		
		private EntityRef<DATTIEC> _DATTIEC1;
		
		private EntityRef<MONAN> _MONAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    partial void OnMaMAChanging(string value);
    partial void OnMaMAChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public DATMONAN()
		{
			this._DATTIEC = default(EntityRef<DATTIEC>);
			this._DATTIEC1 = default(EntityRef<DATTIEC>);
			this._MONAN = default(EntityRef<MONAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					if ((this._DATTIEC.HasLoadedOrAssignedValue || this._DATTIEC1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMA
		{
			get
			{
				return this._MaMA;
			}
			set
			{
				if ((this._MaMA != value))
				{
					if (this._MONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMAChanging(value);
					this.SendPropertyChanging();
					this._MaMA = value;
					this.SendPropertyChanged("MaMA");
					this.OnMaMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATMONAN", Storage="_DATTIEC", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DATTIEC DATTIEC
		{
			get
			{
				return this._DATTIEC.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC.Entity = null;
						previousValue.DATMONANs.Remove(this);
					}
					this._DATTIEC.Entity = value;
					if ((value != null))
					{
						value.DATMONANs.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATMONAN1", Storage="_DATTIEC1", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true)]
		public DATTIEC DATTIEC1
		{
			get
			{
				return this._DATTIEC1.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC1.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC1.Entity = null;
						previousValue.DATMONANs1.Remove(this);
					}
					this._DATTIEC1.Entity = value;
					if ((value != null))
					{
						value.DATMONANs1.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_DATMONAN", Storage="_MONAN", ThisKey="MaMA", OtherKey="MaMA", IsForeignKey=true)]
		public MONAN MONAN
		{
			get
			{
				return this._MONAN.Entity;
			}
			set
			{
				MONAN previousValue = this._MONAN.Entity;
				if (((previousValue != value) 
							|| (this._MONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONAN.Entity = null;
						previousValue.DATMONANs.Remove(this);
					}
					this._MONAN.Entity = value;
					if ((value != null))
					{
						value.DATMONANs.Add(this);
						this._MaMA = value.MaMA;
					}
					else
					{
						this._MaMA = default(string);
					}
					this.SendPropertyChanged("MONAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATTIEC")]
	public partial class DATTIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTiec;
		
		private string _TenTiec;
		
		private string _MaSanh;
		
		private string _MaNV;
		
		private string _MaKH;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<System.DateTime> _NgayToChuc;
		
		private System.Nullable<int> _SoLuongBan;
		
		private System.Nullable<int> _SoLuongKhach;
		
		private string _Buoi;
		
		private string _TinhTrang;
		
		private EntitySet<DATDICHVU> _DATDICHVUs;
		
		private EntitySet<DATDICHVU> _DATDICHVUs1;
		
		private EntitySet<DATMONAN> _DATMONANs;
		
		private EntitySet<DATMONAN> _DATMONANs1;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<Sanh> _Sanh;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    partial void OnTenTiecChanging(string value);
    partial void OnTenTiecChanged();
    partial void OnMaSanhChanging(string value);
    partial void OnMaSanhChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNgayToChucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayToChucChanged();
    partial void OnSoLuongBanChanging(System.Nullable<int> value);
    partial void OnSoLuongBanChanged();
    partial void OnSoLuongKhachChanging(System.Nullable<int> value);
    partial void OnSoLuongKhachChanged();
    partial void OnBuoiChanging(string value);
    partial void OnBuoiChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public DATTIEC()
		{
			this._DATDICHVUs = new EntitySet<DATDICHVU>(new Action<DATDICHVU>(this.attach_DATDICHVUs), new Action<DATDICHVU>(this.detach_DATDICHVUs));
			this._DATDICHVUs1 = new EntitySet<DATDICHVU>(new Action<DATDICHVU>(this.attach_DATDICHVUs1), new Action<DATDICHVU>(this.detach_DATDICHVUs1));
			this._DATMONANs = new EntitySet<DATMONAN>(new Action<DATMONAN>(this.attach_DATMONANs), new Action<DATMONAN>(this.detach_DATMONANs));
			this._DATMONANs1 = new EntitySet<DATMONAN>(new Action<DATMONAN>(this.attach_DATMONANs1), new Action<DATMONAN>(this.detach_DATMONANs1));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._Sanh = default(EntityRef<Sanh>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTiec", DbType="NVarChar(50)")]
		public string TenTiec
		{
			get
			{
				return this._TenTiec;
			}
			set
			{
				if ((this._TenTiec != value))
				{
					this.OnTenTiecChanging(value);
					this.SendPropertyChanging();
					this._TenTiec = value;
					this.SendPropertyChanged("TenTiec");
					this.OnTenTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanh", DbType="Char(10)")]
		public string MaSanh
		{
			get
			{
				return this._MaSanh;
			}
			set
			{
				if ((this._MaSanh != value))
				{
					if (this._Sanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanhChanging(value);
					this.SendPropertyChanging();
					this._MaSanh = value;
					this.SendPropertyChanged("MaSanh");
					this.OnMaSanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayToChuc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayToChuc
		{
			get
			{
				return this._NgayToChuc;
			}
			set
			{
				if ((this._NgayToChuc != value))
				{
					this.OnNgayToChucChanging(value);
					this.SendPropertyChanging();
					this._NgayToChuc = value;
					this.SendPropertyChanged("NgayToChuc");
					this.OnNgayToChucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBan", DbType="Int")]
		public System.Nullable<int> SoLuongBan
		{
			get
			{
				return this._SoLuongBan;
			}
			set
			{
				if ((this._SoLuongBan != value))
				{
					this.OnSoLuongBanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBan = value;
					this.SendPropertyChanged("SoLuongBan");
					this.OnSoLuongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongKhach", DbType="Int")]
		public System.Nullable<int> SoLuongKhach
		{
			get
			{
				return this._SoLuongKhach;
			}
			set
			{
				if ((this._SoLuongKhach != value))
				{
					this.OnSoLuongKhachChanging(value);
					this.SendPropertyChanging();
					this._SoLuongKhach = value;
					this.SendPropertyChanged("SoLuongKhach");
					this.OnSoLuongKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buoi", DbType="NVarChar(20)")]
		public string Buoi
		{
			get
			{
				return this._Buoi;
			}
			set
			{
				if ((this._Buoi != value))
				{
					this.OnBuoiChanging(value);
					this.SendPropertyChanging();
					this._Buoi = value;
					this.SendPropertyChanged("Buoi");
					this.OnBuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATDICHVU", Storage="_DATDICHVUs", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<DATDICHVU> DATDICHVUs
		{
			get
			{
				return this._DATDICHVUs;
			}
			set
			{
				this._DATDICHVUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATDICHVU1", Storage="_DATDICHVUs1", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<DATDICHVU> DATDICHVUs1
		{
			get
			{
				return this._DATDICHVUs1;
			}
			set
			{
				this._DATDICHVUs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATMONAN", Storage="_DATMONANs", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<DATMONAN> DATMONANs
		{
			get
			{
				return this._DATMONANs;
			}
			set
			{
				this._DATMONANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_DATMONAN1", Storage="_DATMONANs1", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<DATMONAN> DATMONANs1
		{
			get
			{
				return this._DATMONANs1;
			}
			set
			{
				this._DATMONANs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_HOADON", Storage="_HOADONs", ThisKey="MaTiec", OtherKey="MaTiec")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanh_DATTIEC", Storage="_Sanh", ThisKey="MaSanh", OtherKey="MaSanh", IsForeignKey=true)]
		public Sanh Sanh
		{
			get
			{
				return this._Sanh.Entity;
			}
			set
			{
				Sanh previousValue = this._Sanh.Entity;
				if (((previousValue != value) 
							|| (this._Sanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sanh.Entity = null;
						previousValue.DATTIECs.Remove(this);
					}
					this._Sanh.Entity = value;
					if ((value != null))
					{
						value.DATTIECs.Add(this);
						this._MaSanh = value.MaSanh;
					}
					else
					{
						this._MaSanh = default(string);
					}
					this.SendPropertyChanged("Sanh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATTIEC", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DATTIECs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DATTIECs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DATTIEC", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.DATTIECs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.DATTIECs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATDICHVUs(DATDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = this;
		}
		
		private void detach_DATDICHVUs(DATDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = null;
		}
		
		private void attach_DATDICHVUs1(DATDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC1 = this;
		}
		
		private void detach_DATDICHVUs1(DATDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC1 = null;
		}
		
		private void attach_DATMONANs(DATMONAN entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = this;
		}
		
		private void detach_DATMONANs(DATMONAN entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = null;
		}
		
		private void attach_DATMONANs1(DATMONAN entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC1 = this;
		}
		
		private void detach_DATMONANs1(DATMONAN entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC1 = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.DATTIEC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private System.Nullable<decimal> _DonGia;
		
		private System.Nullable<System.DateTime> _isDeleted;
		
		private EntitySet<DATDICHVU> _DATDICHVUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnisDeletedChanging(System.Nullable<System.DateTime> value);
    partial void OnisDeletedChanged();
    #endregion
		
		public DICHVU()
		{
			this._DATDICHVUs = new EntitySet<DATDICHVU>(new Action<DATDICHVU>(this.attach_DATDICHVUs), new Action<DATDICHVU>(this.detach_DATDICHVUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Date")]
		public System.Nullable<System.DateTime> isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_DATDICHVU", Storage="_DATDICHVUs", ThisKey="MaDV", OtherKey="MaDV")]
		public EntitySet<DATDICHVU> DATDICHVUs
		{
			get
			{
				return this._DATDICHVUs;
			}
			set
			{
				this._DATDICHVUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATDICHVUs(DATDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = this;
		}
		
		private void detach_DATDICHVUs(DATDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaTiec;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private string _TinhTrang;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private EntityRef<DATTIEC> _DATTIEC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaTiecChanging(string value);
    partial void OnMaTiecChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    #endregion
		
		public HOADON()
		{
			this._DATTIEC = default(EntityRef<DATTIEC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10)")]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					if (this._DATTIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTiecChanging(value);
					this.SendPropertyChanging();
					this._MaTiec = value;
					this.SendPropertyChanged("MaTiec");
					this.OnMaTiecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATTIEC_HOADON", Storage="_DATTIEC", ThisKey="MaTiec", OtherKey="MaTiec", IsForeignKey=true)]
		public DATTIEC DATTIEC
		{
			get
			{
				return this._DATTIEC.Entity;
			}
			set
			{
				DATTIEC previousValue = this._DATTIEC.Entity;
				if (((previousValue != value) 
							|| (this._DATTIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATTIEC.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._DATTIEC.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaTiec = value.MaTiec;
					}
					else
					{
						this._MaTiec = default(string);
					}
					this.SendPropertyChanged("DATTIEC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _GioiTinh;
		
		private string _CMND;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _UserName;
		
		private EntitySet<DATTIEC> _DATTIECs;
		
		private EntityRef<ACCOUNT> _ACCOUNT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._DATTIECs = new EntitySet<DATTIEC>(new Action<DATTIEC>(this.attach_DATTIECs), new Action<DATTIEC>(this.detach_DATTIECs));
			this._ACCOUNT = default(EntityRef<ACCOUNT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(15)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="Char(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					if (this._ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATTIEC", Storage="_DATTIECs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DATTIEC> DATTIECs
		{
			get
			{
				return this._DATTIECs;
			}
			set
			{
				this._DATTIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_KHACHHANG", Storage="_ACCOUNT", ThisKey="UserName", OtherKey="UserName", IsForeignKey=true)]
		public ACCOUNT ACCOUNT
		{
			get
			{
				return this._ACCOUNT.Entity;
			}
			set
			{
				ACCOUNT previousValue = this._ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNT.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._UserName = value.UserName;
					}
					else
					{
						this._UserName = default(string);
					}
					this.SendPropertyChanged("ACCOUNT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MONAN")]
	public partial class MONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMA;
		
		private string _TenMa;
		
		private System.Nullable<decimal> _DonGia;
		
		private string _Loai;
		
		private string _DonViTinh;
		
		private System.Nullable<System.DateTime> _isDeleted;
		
		private EntitySet<DATMONAN> _DATMONANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMAChanging(string value);
    partial void OnMaMAChanged();
    partial void OnTenMaChanging(string value);
    partial void OnTenMaChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnisDeletedChanging(System.Nullable<System.DateTime> value);
    partial void OnisDeletedChanged();
    #endregion
		
		public MONAN()
		{
			this._DATMONANs = new EntitySet<DATMONAN>(new Action<DATMONAN>(this.attach_DATMONANs), new Action<DATMONAN>(this.detach_DATMONANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMA
		{
			get
			{
				return this._MaMA;
			}
			set
			{
				if ((this._MaMA != value))
				{
					this.OnMaMAChanging(value);
					this.SendPropertyChanging();
					this._MaMA = value;
					this.SendPropertyChanged("MaMA");
					this.OnMaMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMa", DbType="NVarChar(50)")]
		public string TenMa
		{
			get
			{
				return this._TenMa;
			}
			set
			{
				if ((this._TenMa != value))
				{
					this.OnTenMaChanging(value);
					this.SendPropertyChanging();
					this._TenMa = value;
					this.SendPropertyChanged("TenMa");
					this.OnTenMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(10)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(10)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Date")]
		public System.Nullable<System.DateTime> isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_DATMONAN", Storage="_DATMONANs", ThisKey="MaMA", OtherKey="MaMA")]
		public EntitySet<DATMONAN> DATMONANs
		{
			get
			{
				return this._DATMONANs;
			}
			set
			{
				this._DATMONANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATMONANs(DATMONAN entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = this;
		}
		
		private void detach_DATMONANs(DATMONAN entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _SDT;
		
		private string _CMND;
		
		private string _MaBP;
		
		private string _ChucVu;
		
		private System.Nullable<decimal> _Luong;
		
		private string _UserName;
		
		private EntitySet<DATTIEC> _DATTIECs;
		
		private EntityRef<ACCOUNT> _ACCOUNT;
		
		private EntityRef<BOPHAN> _BOPHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnMaBPChanging(string value);
    partial void OnMaBPChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnLuongChanging(System.Nullable<decimal> value);
    partial void OnLuongChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._DATTIECs = new EntitySet<DATTIEC>(new Action<DATTIEC>(this.attach_DATTIECs), new Action<DATTIEC>(this.detach_DATTIECs));
			this._ACCOUNT = default(EntityRef<ACCOUNT>);
			this._BOPHAN = default(EntityRef<BOPHAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBP", DbType="Char(10)")]
		public string MaBP
		{
			get
			{
				return this._MaBP;
			}
			set
			{
				if ((this._MaBP != value))
				{
					if (this._BOPHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBPChanging(value);
					this.SendPropertyChanging();
					this._MaBP = value;
					this.SendPropertyChanged("MaBP");
					this.OnMaBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(20)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="Char(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					if (this._ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DATTIEC", Storage="_DATTIECs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<DATTIEC> DATTIECs
		{
			get
			{
				return this._DATTIECs;
			}
			set
			{
				this._DATTIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_NHANVIEN", Storage="_ACCOUNT", ThisKey="UserName", OtherKey="UserName", IsForeignKey=true)]
		public ACCOUNT ACCOUNT
		{
			get
			{
				return this._ACCOUNT.Entity;
			}
			set
			{
				ACCOUNT previousValue = this._ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNT.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._UserName = value.UserName;
					}
					else
					{
						this._UserName = default(string);
					}
					this.SendPropertyChanged("ACCOUNT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOPHAN_NHANVIEN", Storage="_BOPHAN", ThisKey="MaBP", OtherKey="MaBP", IsForeignKey=true)]
		public BOPHAN BOPHAN
		{
			get
			{
				return this._BOPHAN.Entity;
			}
			set
			{
				BOPHAN previousValue = this._BOPHAN.Entity;
				if (((previousValue != value) 
							|| (this._BOPHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BOPHAN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._BOPHAN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._MaBP = value.MaBP;
					}
					else
					{
						this._MaBP = default(string);
					}
					this.SendPropertyChanged("BOPHAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_DATTIECs(DATTIEC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	public partial class ListDichVuDatResult
	{
		
		private string _MaDV;
		
		private string _TenDV;
		
		private System.Nullable<decimal> _DonGia;
		
		private System.Nullable<System.DateTime> _isDeleted;
		
		public ListDichVuDatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this._MaDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this._TenDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Date")]
		public System.Nullable<System.DateTime> isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this._isDeleted = value;
				}
			}
		}
	}
	
	public partial class ShowDatMonResult
	{
		
		private string _MaTiec;
		
		private string _MaMA;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _ThanhTien;
		
		public ShowDatMonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTiec", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaTiec
		{
			get
			{
				return this._MaTiec;
			}
			set
			{
				if ((this._MaTiec != value))
				{
					this._MaTiec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaMA
		{
			get
			{
				return this._MaMA;
			}
			set
			{
				if ((this._MaMA != value))
				{
					this._MaMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
